// Base wholesale catalogue (in NGN wholesale cost per 1,000 units from OneGridHub provider)
export const BASE_SOCIAL_SERVICES = [
  // --- TIKTOK ---
  {
    id: 'tt-followers-hq',
    platform: 'TikTok',
    category: 'TikTok Followers',
    name: 'TikTok Followers [Real & High Retention - Instant Start]',
    type: 'Followers',
    providerRatePer1000: 1800,
    min: 100,
    max: 50000,
    deliverySpeed: '5,000 - 10,000 / day',
    refill: true,
    quality: 'High Quality Active Accounts',
    description: 'Boost your TikTok profile visibility with real looking active followers. Safe and non-drop guarantee.',
    inputLabel: 'TikTok Profile Link or @Username',
    inputPlaceholder: 'https://www.tiktok.com/@username or @username',
    inputType: 'link'
  },
  {
    id: 'tt-likes-fast',
    platform: 'TikTok',
    category: 'TikTok Likes',
    name: 'TikTok Video Likes [Instant Delivery - High Quality]',
    type: 'Likes',
    providerRatePer1000: 600,
    min: 50,
    max: 100000,
    deliverySpeed: '20,000 - 50,000 / day',
    refill: true,
    quality: 'Real Accounts',
    description: 'Instant likes for any TikTok video. Helps boost video on For You Page (FYP).',
    inputLabel: 'TikTok Video URL',
    inputPlaceholder: 'https://www.tiktok.com/@username/video/1234567890',
    inputType: 'link'
  },
  {
    id: 'tt-views-viral',
    platform: 'TikTok',
    category: 'TikTok Views',
    name: 'TikTok Video Views [FYP Algorithm Booster - Ultra Fast]',
    type: 'Views',
    providerRatePer1000: 150,
    min: 500,
    max: 2000000,
    deliverySpeed: '1,000,000+ / day',
    refill: false,
    quality: 'High Speed Algorithm Views',
    description: 'Ultra fast video views to trigger the TikTok algorithm and increase viral reach.',
    inputLabel: 'TikTok Video URL',
    inputPlaceholder: 'https://www.tiktok.com/@username/video/1234567890',
    inputType: 'link'
  },
  {
    id: 'tt-shares-reposts',
    platform: 'TikTok',
    category: 'TikTok Shares & Reposts',
    name: 'TikTok Shares & Reposts [Viral Rank Multiplier]',
    type: 'Shares',
    providerRatePer1000: 750,
    min: 100,
    max: 50000,
    deliverySpeed: '10,000 / day',
    refill: true,
    quality: 'Organic Share Signals',
    description: 'Increases shares & repost counts, one of the strongest ranking signals on TikTok.',
    inputLabel: 'TikTok Video URL',
    inputPlaceholder: 'https://www.tiktok.com/@username/video/1234567890',
    inputType: 'link'
  },
  {
    id: 'tt-comments-custom',
    platform: 'TikTok',
    category: 'TikTok Comments',
    name: 'TikTok Custom Comments [Real Text & Relevant Content]',
    type: 'Comments',
    providerRatePer1000: 4200,
    min: 10,
    max: 2000,
    deliverySpeed: 'Instant Delivery',
    refill: true,
    quality: 'Custom Written Text',
    description: 'Custom positive and engaging comments on your videos to drive social proof.',
    inputLabel: 'TikTok Video URL & Comments (1 per line)',
    inputPlaceholder: 'https://www.tiktok.com/@username/video/1234567890\nGreat content!\nLove this so much!',
    inputType: 'custom_comments'
  },

  // --- INSTAGRAM ---
  {
    id: 'ig-followers-nondrop',
    platform: 'Instagram',
    category: 'Instagram Followers',
    name: 'Instagram Followers [365 Days Refill Guaranteed - Non Drop]',
    type: 'Followers',
    providerRatePer1000: 2100,
    min: 50,
    max: 500000,
    deliverySpeed: '10,000 - 25,000 / day',
    refill: true,
    quality: 'Top Tier High Quality Profiles with Posts',
    description: 'Premium non-drop Instagram followers with full 365-day automated refill warranty.',
    inputLabel: 'Instagram Profile Link or @Username',
    inputPlaceholder: 'https://instagram.com/username or @username',
    inputType: 'link'
  },
  {
    id: 'ig-followers-nigerian',
    platform: 'Instagram',
    category: 'Instagram Followers',
    name: 'Instagram Followers [Targeted Nigerian & African Active]',
    type: 'Followers',
    providerRatePer1000: 4500,
    min: 50,
    max: 25000,
    deliverySpeed: '2,000 - 5,000 / day',
    refill: true,
    quality: '100% Real African / Nigerian Names',
    description: 'Targeted Nigerian and African profiles for local businesses, influencers, and brands.',
    inputLabel: 'Instagram Profile Link or @Username',
    inputPlaceholder: 'https://instagram.com/username or @username',
    inputType: 'link'
  },
  {
    id: 'ig-likes-superfast',
    platform: 'Instagram',
    category: 'Instagram Likes',
    name: 'Instagram Post & Reels Likes [Instant Start - Super Fast]',
    type: 'Likes',
    providerRatePer1000: 520,
    min: 50,
    max: 100000,
    deliverySpeed: '50,000 / day',
    refill: true,
    quality: 'Real Active Profiles',
    description: 'Instant likes for Instagram photos, carousels, and reels. Starts within 30 seconds.',
    inputLabel: 'Instagram Post / Reel URL',
    inputPlaceholder: 'https://instagram.com/p/ABCDEF12345/ or reel link',
    inputType: 'link'
  },
  {
    id: 'ig-views-reels',
    platform: 'Instagram',
    category: 'Instagram Views',
    name: 'Instagram Reels Views [Explore Feed Algorithm Trigger]',
    type: 'Views',
    providerRatePer1000: 180,
    min: 500,
    max: 5000000,
    deliverySpeed: '1,000,000+ / day',
    refill: false,
    quality: 'High Retention Views',
    description: 'High retention Reels video views to push your video into Instagram Explore feed.',
    inputLabel: 'Instagram Reel URL',
    inputPlaceholder: 'https://instagram.com/reel/C0123456789/',
    inputType: 'link'
  },
  {
    id: 'ig-story-views',
    platform: 'Instagram',
    category: 'Instagram Views',
    name: 'Instagram Story Views & Impressions [All Active Stories]',
    type: 'Views',
    providerRatePer1000: 380,
    min: 100,
    max: 50000,
    deliverySpeed: 'Instant Delivery',
    refill: false,
    quality: 'Active Profiles',
    description: 'Views on all current active Instagram stories on the account.',
    inputLabel: 'Instagram Profile Link or @Username',
    inputPlaceholder: 'https://instagram.com/username or @username',
    inputType: 'link'
  },

  // --- FACEBOOK ---
  {
    id: 'fb-page-followers',
    platform: 'Facebook',
    category: 'Facebook Followers',
    name: 'Facebook Page Followers & Likes [Real Aged Profiles]',
    type: 'Followers',
    providerRatePer1000: 2600,
    min: 100,
    max: 100000,
    deliverySpeed: '5,000 - 10,000 / day',
    refill: true,
    quality: 'Aged Real Facebook Accounts',
    description: 'Build credibility and audience for Facebook Business and Creator pages.',
    inputLabel: 'Facebook Page URL',
    inputPlaceholder: 'https://www.facebook.com/yourpagename',
    inputType: 'link'
  },
  {
    id: 'fb-profile-followers',
    platform: 'Facebook',
    category: 'Facebook Followers',
    name: 'Facebook Personal Profile Followers [High Quality]',
    type: 'Followers',
    providerRatePer1000: 2200,
    min: 100,
    max: 50000,
    deliverySpeed: '5,000 / day',
    refill: true,
    quality: 'Real Accounts',
    description: 'Followers for personal Facebook profiles and public figure pages.',
    inputLabel: 'Facebook Profile URL',
    inputPlaceholder: 'https://www.facebook.com/profile.php?id=12345 or username',
    inputType: 'link'
  },
  {
    id: 'fb-post-likes',
    platform: 'Facebook',
    category: 'Facebook Likes',
    name: 'Facebook Post Likes & Reactions (Love / Care / Wow / Haha)',
    type: 'Likes',
    providerRatePer1000: 700,
    min: 50,
    max: 20000,
    deliverySpeed: '10,000 / day',
    refill: true,
    quality: 'Real Reactions',
    description: 'Likes and emotional reactions for Facebook public posts and photos.',
    inputLabel: 'Facebook Post URL',
    inputPlaceholder: 'https://www.facebook.com/permalink.php?story_fbid=...',
    inputType: 'link'
  },
  {
    id: 'fb-video-views',
    platform: 'Facebook',
    category: 'Facebook Views',
    name: 'Facebook Video & Reel Views [Monetization Safe]',
    type: 'Views',
    providerRatePer1000: 320,
    min: 500,
    max: 500000,
    deliverySpeed: '100,000 / day',
    refill: false,
    quality: 'High Retention Video Views',
    description: 'Monetization-safe video views for Facebook Watch, Page Videos, and Reels.',
    inputLabel: 'Facebook Video URL',
    inputPlaceholder: 'https://www.facebook.com/watch/?v=1234567890',
    inputType: 'link'
  },
  {
    id: 'fb-group-members',
    platform: 'Facebook',
    category: 'Facebook Members',
    name: 'Facebook Group Members [Public or Private Groups]',
    type: 'Members',
    providerRatePer1000: 3200,
    min: 100,
    max: 25000,
    deliverySpeed: '3,000 - 5,000 / day',
    refill: true,
    quality: 'Active Profiles',
    description: 'Add active members to grow your Facebook community group.',
    inputLabel: 'Facebook Group URL',
    inputPlaceholder: 'https://www.facebook.com/groups/yourgroupname',
    inputType: 'link'
  },

  // --- YOUTUBE ---
  {
    id: 'yt-subscribers-hq',
    platform: 'YouTube',
    category: 'YouTube Subscribers',
    name: 'YouTube Subscribers [Non-Drop 30 Days Refill Guarantee]',
    type: 'Subscribers',
    providerRatePer1000: 8900,
    min: 50,
    max: 100000,
    deliverySpeed: '500 - 1,500 / day',
    refill: true,
    quality: 'Real Accounts with Activity',
    description: 'Organic speed subscribers to grow your YouTube channel safely without drops.',
    inputLabel: 'YouTube Channel URL',
    inputPlaceholder: 'https://www.youtube.com/@channelname or channel link',
    inputType: 'link'
  },
  {
    id: 'yt-views-retention',
    platform: 'YouTube',
    category: 'YouTube Views',
    name: 'YouTube High Retention Views [Monetization & Ads Safe]',
    type: 'Views',
    providerRatePer1000: 1500,
    min: 500,
    max: 1000000,
    deliverySpeed: '10,000 - 25,000 / day',
    refill: true,
    quality: 'Monetization Safe Worldwide Views',
    description: 'High watch-time retention views to boost YouTube search ranking and suggested videos.',
    inputLabel: 'YouTube Video URL',
    inputPlaceholder: 'https://www.youtube.com/watch?v=ABCDEF12345',
    inputType: 'link'
  },
  {
    id: 'yt-watch-hours',
    platform: 'YouTube',
    category: 'YouTube Watch Hours',
    name: 'YouTube 4,000 Watch Hours Package [Monetization Enabler]',
    type: 'Watch Hours',
    providerRatePer1000: 24000,
    min: 100,
    max: 4000,
    deliverySpeed: '500 - 1,000 Hours / day',
    refill: true,
    quality: 'Monetization Approved Watch-time',
    description: 'Complete the YouTube Partner Program (YPP) 4,000 hours requirement. Requires 60+ min video.',
    inputLabel: 'YouTube 60+ Min Video URL',
    inputPlaceholder: 'https://www.youtube.com/watch?v=ABCDEF12345 (Video must be 60+ minutes)',
    inputType: 'link'
  },
  {
    id: 'yt-likes-instant',
    platform: 'YouTube',
    category: 'YouTube Likes',
    name: 'YouTube Video Likes [Instant High Retention]',
    type: 'Likes',
    providerRatePer1000: 1100,
    min: 50,
    max: 50000,
    deliverySpeed: '10,000 / day',
    refill: true,
    quality: 'Real Accounts',
    description: 'Instant likes on any YouTube video to build instant credibility.',
    inputLabel: 'YouTube Video URL',
    inputPlaceholder: 'https://www.youtube.com/watch?v=ABCDEF12345',
    inputType: 'link'
  },
  {
    id: 'yt-shorts-views',
    platform: 'YouTube',
    category: 'YouTube Views',
    name: 'YouTube Shorts Views [Viral Algorithm Boost]',
    type: 'Views',
    providerRatePer1000: 280,
    min: 500,
    max: 1000000,
    deliverySpeed: '100,000+ / day',
    refill: false,
    quality: 'Ultra Fast Shorts Views',
    description: 'Instant YouTube Shorts views to hit the shorts feed algorithm.',
    inputLabel: 'YouTube Shorts URL',
    inputPlaceholder: 'https://youtube.com/shorts/ABCDEF12345',
    inputType: 'link'
  },

  // --- TWITTER / X ---
  {
    id: 'x-followers-hq',
    platform: 'Twitter / X',
    category: 'X / Twitter Followers',
    name: 'X (Twitter) Followers [HQ Aged Profiles with Bio & PFP]',
    type: 'Followers',
    providerRatePer1000: 4200,
    min: 50,
    max: 50000,
    deliverySpeed: '2,000 - 5,000 / day',
    refill: true,
    quality: 'Aged Active Accounts',
    description: 'Authentic-looking X (Twitter) followers to enhance profile authority.',
    inputLabel: 'X / Twitter Profile Link or @Username',
    inputPlaceholder: 'https://x.com/username or @username',
    inputType: 'link'
  },
  {
    id: 'x-likes-retweets',
    platform: 'Twitter / X',
    category: 'X / Twitter Engagement',
    name: 'X (Twitter) Post Likes & Retweets [Instant Speed]',
    type: 'Likes',
    providerRatePer1000: 1600,
    min: 50,
    max: 25000,
    deliverySpeed: '10,000 / day',
    refill: true,
    quality: 'Instant Real Profiles',
    description: 'Instant likes and reposts for tweets to trigger timeline trends.',
    inputLabel: 'X / Twitter Post (Tweet) URL',
    inputPlaceholder: 'https://x.com/username/status/1234567890',
    inputType: 'link'
  },
  {
    id: 'x-views-impressions',
    platform: 'Twitter / X',
    category: 'X / Twitter Views',
    name: 'X (Twitter) Tweet Impressions & Views [Creator Monetization]',
    type: 'Views',
    providerRatePer1000: 140,
    min: 1000,
    max: 10000000,
    deliverySpeed: '500,000+ / day',
    refill: false,
    quality: 'Organic Impressing Counts',
    description: 'Massive impressions to meet the 5M impressions requirement for X Creator Revenue Sharing.',
    inputLabel: 'X / Twitter Post (Tweet) URL',
    inputPlaceholder: 'https://x.com/username/status/1234567890',
    inputType: 'link'
  },

  // --- TELEGRAM ---
  {
    id: 'tg-members-nondrop',
    platform: 'Telegram',
    category: 'Telegram Members',
    name: 'Telegram Channel / Group Members [Zero Drop 90 Days Guarantee]',
    type: 'Members',
    providerRatePer1000: 1300,
    min: 100,
    max: 100000,
    deliverySpeed: '20,000 / day',
    refill: true,
    quality: 'Zero Drop Real Accounts',
    description: 'Non-drop active channel and group members with 90 days automatic refill.',
    inputLabel: 'Telegram Channel / Group Link or @Handle',
    inputPlaceholder: 'https://t.me/channelname or @channelname',
    inputType: 'link'
  },
  {
    id: 'tg-post-views',
    platform: 'Telegram',
    category: 'Telegram Views',
    name: 'Telegram Post Views [Instant View Counts]',
    type: 'Views',
    providerRatePer1000: 110,
    min: 500,
    max: 500000,
    deliverySpeed: 'Instant Delivery',
    refill: false,
    quality: 'Instant Views',
    description: 'Add views to any Telegram channel post instantly.',
    inputLabel: 'Telegram Post Link',
    inputPlaceholder: 'https://t.me/channelname/123',
    inputType: 'link'
  },
  {
    id: 'tg-reactions-positive',
    platform: 'Telegram',
    category: 'Telegram Reactions',
    name: 'Telegram Positive Reactions (👍 / ❤️ / 🔥 / 🚀 / 👏)',
    type: 'Likes',
    providerRatePer1000: 400,
    min: 100,
    max: 20000,
    deliverySpeed: 'Instant Delivery',
    refill: false,
    quality: 'Natural Mix of Top Emojis',
    description: 'Boost engagement with natural emoji reactions on Telegram posts.',
    inputLabel: 'Telegram Post Link',
    inputPlaceholder: 'https://t.me/channelname/123',
    inputType: 'link'
  },

  // --- SPOTIFY & MUSIC ---
  {
    id: 'sp-artist-followers',
    platform: 'Spotify & Music',
    category: 'Spotify Followers',
    name: 'Spotify Artist Followers [Real Music Listeners]',
    type: 'Followers',
    providerRatePer1000: 3100,
    min: 100,
    max: 50000,
    deliverySpeed: '2,000 / day',
    refill: true,
    quality: 'Active Spotify Accounts',
    description: 'Grow your Spotify Artist profile followers to boost algorithmic playlist placement.',
    inputLabel: 'Spotify Artist URL',
    inputPlaceholder: 'https://open.spotify.com/artist/ABCDEF12345',
    inputType: 'link'
  },
  {
    id: 'sp-track-plays',
    platform: 'Spotify & Music',
    category: 'Spotify Plays',
    name: 'Spotify Track Streams / Plays [Royalty & Algorithmic Mix]',
    type: 'Plays',
    providerRatePer1000: 1100,
    min: 1000,
    max: 500000,
    deliverySpeed: '10,000 / day',
    refill: true,
    quality: 'USA / Europe / Global High Retention',
    description: 'High retention streams to trigger Release Radar and Discover Weekly algorithms.',
    inputLabel: 'Spotify Track / Album URL',
    inputPlaceholder: 'https://open.spotify.com/track/ABCDEF12345',
    inputType: 'link'
  },

  // --- THREADS ---
  {
    id: 'thr-followers-meta',
    platform: 'Threads',
    category: 'Threads Followers',
    name: 'Threads Followers [Meta Integrated Real Profiles]',
    type: 'Followers',
    providerRatePer1000: 3600,
    min: 50,
    max: 25000,
    deliverySpeed: '3,000 / day',
    refill: true,
    quality: 'High Quality Meta Linked Profiles',
    description: 'Grow your Threads audience fast with real-looking meta accounts.',
    inputLabel: 'Threads Profile URL or @Username',
    inputPlaceholder: 'https://www.threads.net/@username or @username',
    inputType: 'link'
  },
  {
    id: 'thr-likes-reposts',
    platform: 'Threads',
    category: 'Threads Likes',
    name: 'Threads Post Likes & Reposts [Instant Delivery]',
    type: 'Likes',
    providerRatePer1000: 890,
    min: 50,
    max: 20000,
    deliverySpeed: '5,000 / day',
    refill: true,
    quality: 'Real Accounts',
    description: 'Instant engagement for Threads posts.',
    inputLabel: 'Threads Post URL',
    inputPlaceholder: 'https://www.threads.net/@username/post/ABCDEF123',
    inputType: 'link'
  },

  // --- LINKEDIN ---
  {
    id: 'li-followers-connections',
    platform: 'LinkedIn',
    category: 'LinkedIn Followers',
    name: 'LinkedIn Profile & Company Page Followers [HQ Professional Accounts]',
    type: 'Followers',
    providerRatePer1000: 5200,
    min: 50,
    max: 20000,
    deliverySpeed: '1,000 - 2,000 / day',
    refill: true,
    quality: 'Aged Business & Professional Profiles',
    description: 'Elevate your B2B credibility and professional network with high quality profile followers.',
    inputLabel: 'LinkedIn Profile / Company Page URL',
    inputPlaceholder: 'https://www.linkedin.com/in/username or company page',
    inputType: 'link'
  },
  {
    id: 'li-post-likes',
    platform: 'LinkedIn',
    category: 'LinkedIn Likes',
    name: 'LinkedIn Post Likes & Celebrates [Instant Algorithm Boost]',
    type: 'Likes',
    providerRatePer1000: 1850,
    min: 25,
    max: 10000,
    deliverySpeed: '2,000 / day',
    refill: true,
    quality: 'Real Business Profiles',
    description: 'Boost engagement on LinkedIn articles and posts to expand feed reach.',
    inputLabel: 'LinkedIn Post URL',
    inputPlaceholder: 'https://www.linkedin.com/posts/...',
    inputType: 'link'
  },

  // --- DISCORD ---
  {
    id: 'dc-server-members',
    platform: 'Discord',
    category: 'Discord Members',
    name: 'Discord Server Members [Online & Offline Mix - High Quality]',
    type: 'Members',
    providerRatePer1000: 2900,
    min: 100,
    max: 50000,
    deliverySpeed: '5,000 / day',
    refill: true,
    quality: 'Realistic Avatars & Nicknames',
    description: 'Grow your Discord gaming or Web3 server population instantly.',
    inputLabel: 'Discord Server Invite Link (Never Expiring)',
    inputPlaceholder: 'https://discord.gg/yourinvitecode',
    inputType: 'link'
  },

  // --- TWITCH & STREAMING ---
  {
    id: 'tw-channel-followers',
    platform: 'Twitch & Streaming',
    category: 'Twitch Followers',
    name: 'Twitch Channel Followers [Affiliate & Partner Booster]',
    type: 'Followers',
    providerRatePer1000: 2400,
    min: 50,
    max: 50000,
    deliverySpeed: '5,000 / day',
    refill: true,
    quality: 'Real Gamer Profiles',
    description: 'Reach Twitch Affiliate status faster with high retention channel followers.',
    inputLabel: 'Twitch Channel URL',
    inputPlaceholder: 'https://twitch.tv/channelname',
    inputType: 'link'
  },

  // --- SNAPCHAT ---
  {
    id: 'sc-public-followers',
    platform: 'Snapchat',
    category: 'Snapchat Followers',
    name: 'Snapchat Public Profile Followers [High Quality Global]',
    type: 'Followers',
    providerRatePer1000: 4800,
    min: 50,
    max: 20000,
    deliverySpeed: '1,000 / day',
    refill: true,
    quality: 'HQ Active Snapchat Profiles',
    description: 'Grow your Snapchat public creator profile audience and reach.',
    inputLabel: 'Snapchat Profile URL or @Username',
    inputPlaceholder: 'https://www.snapchat.com/add/username or @username',
    inputType: 'link'
  },

  // --- REDDIT ---
  {
    id: 'rd-post-upvotes',
    platform: 'Reddit',
    category: 'Reddit Upvotes',
    name: 'Reddit Post Upvotes [Frontpage & Subreddit Top Booster]',
    type: 'Likes',
    providerRatePer1000: 6500,
    min: 20,
    max: 5000,
    deliverySpeed: '500 / hour',
    refill: false,
    quality: 'Aged Reddit Accounts with Karma',
    description: 'Send upvotes to any Reddit submission to rank higher on Hot and Top feeds.',
    inputLabel: 'Reddit Post URL',
    inputPlaceholder: 'https://reddit.com/r/subreddit/comments/...',
    inputType: 'link'
  },

  // --- REVIEWS & RATINGS ---
  {
    id: 'rev-google-5star',
    platform: 'Reviews & Ratings',
    category: 'Google Maps Reviews',
    name: 'Google Maps Business 5-Star Reviews [Custom Written & Geo-Targeted]',
    type: 'Reviews',
    providerRatePer1000: 18000,
    min: 5,
    max: 500,
    deliverySpeed: '3 - 5 / day (Natural Drip)',
    refill: true,
    quality: 'Aged Local Google Accounts (100% Non-Drop Guarantee)',
    description: 'Boost local business trust and SEO ranking with custom high-rating reviews.',
    inputLabel: 'Google Maps Business Link + Custom Review Text',
    inputPlaceholder: 'https://maps.app.goo.gl/... \nInclude review details per line',
    inputType: 'custom_comments'
  },

  // --- WEBSITE TRAFFIC & SEO ---
  {
    id: 'web-traffic-organic',
    platform: 'Website Traffic & SEO',
    category: 'Website Visitors',
    name: 'High Quality Organic Web Traffic [Google Search Keywords - Google Analytics Tracked]',
    type: 'Website Visits',
    providerRatePer1000: 850,
    min: 1000,
    max: 5000000,
    deliverySpeed: '50,000 / day',
    refill: false,
    quality: '100% Google Analytics 4 (GA4) Trackable Visitors',
    description: 'Real desktop and mobile visitors with 60s+ session duration to lower bounce rate and boost SEO.',
    inputLabel: 'Website URL (Must include https://)',
    inputPlaceholder: 'https://yourwebsite.com',
    inputType: 'link'
  },

  // --- WHATSAPP ---
  {
    id: 'wa-channel-members',
    platform: 'WhatsApp',
    category: 'WhatsApp Channel Members',
    name: 'WhatsApp Channel Followers & Members [Real Active Nigerian & Global]',
    type: 'Members',
    providerRatePer1000: 2200,
    min: 50,
    max: 50000,
    deliverySpeed: '5,000 / day',
    refill: true,
    quality: 'Active WhatsApp Mobile Numbers',
    description: 'Boost WhatsApp Channel subscriber counts to build social proof and reach.',
    inputLabel: 'WhatsApp Channel Invite Link',
    inputPlaceholder: 'https://whatsapp.com/channel/0029Va...',
    inputType: 'link'
  }
];
